### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Maniues** [sda97ghb/realtest#32]
What is license for this mod?

**Comment by sda97ghb** [comment]
IDK, I think GPL v3 will fit the best. Anyway I have not worked on this project for a long time, so I think you may fork it and do anything you want.

**Comment by Maniues** [comment]
> 
> 
> IDK, I think GPL v3 will fit the best. Anyway I have not worked on this project for a long time, so I think you may fork it and do anything you want.

So, can you add license file to this repo?

**Comment by sda97ghb** [comment]
I added the LICENSE file with the GPL v3 license. Textures license is CC BY.
